package es.caib.gestoli.front.sistra.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.4
 * Wed Mar 30 10:49:14 CEST 2011
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "urn:es:caib:sistra:ws:v2:services", name = "SistraFacade")
@XmlSeeAlso({ObjectFactory.class})
public interface SistraFacade {

    @ResponseWrapper(localName = "realizarConsultaResponse", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade", className = "es.caib.gestoli.front.sistra.ws.RealizarConsultaResponse")
    @RequestWrapper(localName = "realizarConsulta", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade", className = "es.caib.gestoli.front.sistra.ws.RealizarConsulta")
    @WebResult(name = "realizarConsultaReturn", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
    @WebMethod
    public es.caib.gestoli.front.sistra.ws.DocumentosConsulta realizarConsulta(
        @WebParam(name = "identificadorTramite", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
        java.lang.String identificadorTramite,
        @WebParam(name = "forms", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
        es.caib.gestoli.front.sistra.ws.FormulariosConsulta forms
    ) throws SistraFacadeException_Exception;

    @ResponseWrapper(localName = "obtenerDominioResponse", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade", className = "es.caib.gestoli.front.sistra.ws.ObtenerDominioResponse")
    @RequestWrapper(localName = "obtenerDominio", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade", className = "es.caib.gestoli.front.sistra.ws.ObtenerDominio")
    @WebResult(name = "obtenerDominioReturn", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
    @WebMethod
    public es.caib.gestoli.front.sistra.ws.ValoresDominio obtenerDominio(
        @WebParam(name = "id", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
        java.lang.String id,
        @WebParam(name = "parametros", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
        es.caib.gestoli.front.sistra.ws.ParametrosDominio parametros
    ) throws SistraFacadeException_Exception;
}
