
package es.caib.gestoli.front.sistra.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.4
 * Wed Mar 30 10:49:14 CEST 2011
 * Generated source version: 2.2.4
 * 
 */

@WebFault(name = "fault", targetNamespace = "urn:es:caib:sistra:ws:v2:model:SistraFacade")
public class SistraFacadeException_Exception extends Exception {
    public static final long serialVersionUID = 20110330104914L;
    
    private es.caib.gestoli.front.sistra.ws.SistraFacadeException fault;

    public SistraFacadeException_Exception() {
        super();
    }
    
    public SistraFacadeException_Exception(String message) {
        super(message);
    }
    
    public SistraFacadeException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SistraFacadeException_Exception(String message, es.caib.gestoli.front.sistra.ws.SistraFacadeException fault) {
        super(message);
        this.fault = fault;
    }

    public SistraFacadeException_Exception(String message, es.caib.gestoli.front.sistra.ws.SistraFacadeException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public es.caib.gestoli.front.sistra.ws.SistraFacadeException getFaultInfo() {
        return this.fault;
    }
}
