/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Home interface for OliArxiuEjb.
 */
public interface OliArxiuEjbHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliArxiuEjb";
   public static final String JNDI_NAME="OliArxiuEjb";

   public es.caib.gestoli.logic.interfaces.OliArxiuEjb create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
