/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Local home interface for OliArxiuEjb.
 */
public interface OliArxiuEjbLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliArxiuEjbLocal";
   public static final String JNDI_NAME="OliArxiuEjbLocal";

   public es.caib.gestoli.logic.interfaces.OliArxiuEjbLocal create()
      throws javax.ejb.CreateException;

}
