/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Home interface for OliConsultaEjb.
 */
public interface OliConsultaEjbHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliConsultaEjb";
   public static final String JNDI_NAME="OliConsultaEjb";

   public es.caib.gestoli.logic.interfaces.OliConsultaEjb create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
