/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Local home interface for OliConsultaEjb.
 */
public interface OliConsultaEjbLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliConsultaEjbLocal";
   public static final String JNDI_NAME="OliConsultaEjbLocal";

   public es.caib.gestoli.logic.interfaces.OliConsultaEjbLocal create()
      throws javax.ejb.CreateException;

}
