/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Home interface for OliFrontOfficeEjb.
 */
public interface OliFrontOfficeEjbHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliFrontOfficeEjb";
   public static final String JNDI_NAME="OliFrontOfficeEjb";

   public es.caib.gestoli.logic.interfaces.OliFrontOfficeEjb create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
