/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Local home interface for OliFrontOfficeEjb.
 */
public interface OliFrontOfficeEjbLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliFrontOfficeEjbLocal";
   public static final String JNDI_NAME="OliFrontOfficeEjbLocal";

   public es.caib.gestoli.logic.interfaces.OliFrontOfficeEjbLocal create()
      throws javax.ejb.CreateException;

}
