/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Local home interface for OliInfraestructuraEjb.
 */
public interface OliInfraestructuraEjbLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliInfraestructuraEjbLocal";
   public static final String JNDI_NAME="OliInfraestructuraEjbLocal";

   public es.caib.gestoli.logic.interfaces.OliInfraestructuraEjbLocal create()
      throws javax.ejb.CreateException;

}
