/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Local home interface for OliInformacioEjb.
 * @generated 
 */
public interface OliInformacioEjbLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliInformacioEjbLocal";
   public static final String JNDI_NAME="OliInformacioEjbLocal";

   public es.caib.gestoli.logic.interfaces.OliInformacioEjbLocal create()
      throws javax.ejb.CreateException;

}
