/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Local home interface for OliInitDBEjb.
 */
public interface OliInitDBEjbLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliInitDBEjbLocal";
   public static final String JNDI_NAME="OliInitDBEjbLocal";

   public es.caib.gestoli.logic.interfaces.OliInitDBEjbLocal create()
      throws javax.ejb.CreateException;

}
