/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Home interface for OliInformacioEjb.
 * @generated 
 */
public interface OliInformacioEjbHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliInformacioEjb";
   public static final String JNDI_NAME="OliInformacioEjb";

   public es.caib.gestoli.logic.interfaces.OliInformacioEjb create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
