/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Home interface for OliInfraestructuraEjb.
 */
public interface OliInfraestructuraEjbHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliInfraestructuraEjb";
   public static final String JNDI_NAME="OliInfraestructuraEjb";

   public es.caib.gestoli.logic.interfaces.OliInfraestructuraEjb create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
