/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Home interface for OliProcessosEjb.
 * @generated 
 */
public interface OliProcessosEjbHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliProcessosEjb";
   public static final String JNDI_NAME="OliProcessosEjb";

   public es.caib.gestoli.logic.interfaces.OliProcessosEjb create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
