/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Local home interface for OliProcessosEjb.
 * @generated 
 */
public interface OliProcessosEjbLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliProcessosEjbLocal";
   public static final String JNDI_NAME="OliProcessosEjbLocal";

   public es.caib.gestoli.logic.interfaces.OliProcessosEjbLocal create()
      throws javax.ejb.CreateException;

}
