/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Local interface for OliQualitatEjb.
 */
public interface OliQualitatEjbLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void ejbRemove(  ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void crearDescripcioInstalacio( es.caib.gestoli.logic.model.QualitatDescripcioInstalacio q ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarDescripcioInstalacio( es.caib.gestoli.logic.model.QualitatDescripcioInstalacio q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatDescripcioInstalacio descripcioInstalacioAmbId( java.lang.Long id ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatDescripcioInstalacio descripcioInstalacioByEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long descripcioEquipCrear( es.caib.gestoli.logic.model.QualitatDescripcioEquip q ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarDescripcioEquip( es.caib.gestoli.logic.model.QualitatDescripcioEquip q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatDescripcioEquip getQualitatDescripcioEquipById( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection getQualitatDescripcioEquipsByEstabliment( java.lang.Long establimentId ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection vehiclesByEstabliment( java.lang.Long establimentId ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void qualitatDescripcioEquipEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearDescripcioPersonal( es.caib.gestoli.logic.model.QualitatDescripcioPersonal q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatDescripcioPersonal personalAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection personalCercaTotsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void personalEsborrar( java.lang.Long id ) ;

   /**
    * Devuelve una lista de documentos
    * @return collection <!-- begin-xdoclet-definition -->
    */
   public java.util.List documentsByPersonal( java.lang.Long idPersonal ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarPuestoTreball( es.caib.gestoli.logic.model.QualitatPuestoTreball q ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPuestoTreball( es.caib.gestoli.logic.model.QualitatPuestoTreball q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPuestoTreball puestoAmbId( java.lang.Long id ) ;

   /**
    * Cerca tots els carrecs de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection puestoCercaTotsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Cerca tot els carrecs de l'establiment per nivell Jerarquic<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection puestoCercaTotsPerNivell( java.lang.Long idEstabliment,java.lang.Integer nivell ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void puestoEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaFormacio( es.caib.gestoli.logic.model.QualitatPlaFormacio q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaFormacio formacioAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection formacioCercaTotsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void formacioEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearEvaluacio( es.caib.gestoli.logic.model.QualitatFormacioEvaluacio q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatFormacioEvaluacio evaluacioAmbId( java.lang.Long id ) ;

   /**
    * Cerca totes les evaluacions de la formacio <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection evaluacioCercaTotsPerFormacio( java.lang.Long idFormacio ) ;

   /**
    * Cerca totes les evaluacions del treballador <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection evaluacioCercaTotsPerTreballador( java.lang.Long idTreballador ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void evaluacioEsborrar( java.lang.Long id ) ;

   /**
    * Cerca totes les evaluacions del treballador <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long proveidorCrear( es.caib.gestoli.logic.model.QualitatProveidor q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatProveidor proveidorAmbId( java.lang.Long id ) ;

   /**
    * Cerca tots els proveidors de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection proveidorsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void proveidorEsborrar( java.lang.Long id ) ;

   /**
    * Cerca totes les evaluacions del treballador <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.GestorDocumentalInformacio informacioAmbId( java.lang.Integer id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public boolean usuariHaLeido( java.lang.Long idUsu,java.lang.Integer idInfo ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void usuariLeeInfo( java.lang.Long idUsu,es.caib.gestoli.logic.model.GestorDocumentalInformacio info ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.List documentsByInformacio( java.lang.Integer idInformacio ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.GestorDocumentalCategoriaInformacio categoriaInformacioAmbId( java.lang.Integer id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection categoriaInformacioFindAll(  ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection llistatInformacioFiltreIEstat( java.lang.Integer categoria,int estat ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection llistatInformacioIEstat( int estat ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection llistatInformacio(  ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public boolean existenInformacionesAsociadasCategoria( java.lang.Integer id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void categoriaInformacioEsborrar( java.lang.Integer id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Integer informacioCategoriaCrear( java.lang.String nom,java.lang.String desc ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void informacioCategoriaModificar( java.lang.Integer id,java.lang.String nom,java.lang.String desc ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public boolean existeOtraCategoriaConNombre( java.lang.String nom,java.lang.Integer id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void documentEsborrar( java.lang.Integer id ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.lang.Integer informacioCrear( es.caib.gestoli.logic.model.GestorDocumentalInformacio informacio ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public void informacioModificar( es.caib.gestoli.logic.model.GestorDocumentalInformacio informacio,java.lang.Boolean informar ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public void informacioEsborrar( es.caib.gestoli.logic.model.GestorDocumentalInformacio informacio ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public void documentCrear( es.caib.gestoli.logic.model.GestorDocumentalDocument document,es.caib.gestoli.logic.model.Arxiu arxiu ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public void documentModificar( es.caib.gestoli.logic.model.GestorDocumentalDocument document,es.caib.gestoli.logic.model.Arxiu arxiu ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.GestorDocumentalDocument documentAmbId( java.lang.Integer id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearSubministre( es.caib.gestoli.logic.model.QualitatSubministre q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatSubministre subministreAmbId( java.lang.Long id ) ;

   /**
    * Cerca tots els subministres d'un proveidor<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection subministrePerProveidor( java.lang.Long idProveidor ) ;

   /**
    * Cerca tots els subministres d'un establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection subministresPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void subministreEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearProveidorRGSA( es.caib.gestoli.logic.model.QualitatProveidorRGSA q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatProveidorRGSA proveidorRGSAAmbId( java.lang.Long id ) ;

   /**
    * Cerca tots els proveidorRGSAs d'un proveidor<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection proveidorRGSAPerProveidor( java.lang.Long idProveidor ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void proveidorRGSAEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearProveidorAvaluacio( es.caib.gestoli.logic.model.QualitatProveidorAvaluacio q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatProveidorAvaluacio proveidorAvaluacioAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection avaluacionsPerProveidor( java.lang.Long idProveidor ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void proveidorAvaluacioEsborrar( java.lang.Long id ) ;

   /**
    * Cerca totes les evaluacions del treballador <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarPlaNeteja( es.caib.gestoli.logic.model.QualitatPlaNeteja q ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaManteniment( es.caib.gestoli.logic.model.QualitatPlaManteniment q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaManteniment mantenimentAmbId( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaNeteja( es.caib.gestoli.logic.model.QualitatPlaNeteja q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaNeteja plaNetejaAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection plansNetejaPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void plaNetejaEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaNetejaRealitzacio( es.caib.gestoli.logic.model.QualitatPlaNetejaRealitzacio q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaNetejaRealitzacio netejaRealitzacioAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection netejaRealitzacioPerPlaNeteja( java.lang.Long idManteniment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void netejaRealitzacioEsborrar( java.lang.Long id ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaNetejaVerificacio netejaVerificacioAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection netejaVerificacioPerPlaNeteja( java.lang.Long idNeteja ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void netejaVerificacioEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaNetejaVerificacio( es.caib.gestoli.logic.model.QualitatPlaNetejaVerificacio q ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection mantenimentCercaTotsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void mantenimentEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaMantenimentControl( es.caib.gestoli.logic.model.QualitatPlaMantenimentControl q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaMantenimentControl mantenimentControlAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection mantenimentControlCercaTotsPerManteniment( java.lang.Long idManteniment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void mantenimentControlEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearControlPlagues( es.caib.gestoli.logic.model.QualitatControlPlagues q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatControlPlagues controlPlaguesAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection controlPlaguesCercaTotsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void controlPlaguesEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearControlPlaguesVerificacio( es.caib.gestoli.logic.model.QualitatControlPlaguesVerificacio q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatControlPlaguesVerificacio controlPlaguesVerificacioAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection controlPlaguesVerificacioCercaTotsPerPlaga( java.lang.Long idPlaga ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void controlPlaguesVerificacioEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaControlTransport( es.caib.gestoli.logic.model.QualitatPlaControlTransport q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaControlTransport plaControlTransportAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection plansControlTransportPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void plaControlTransportEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearNoConformitat( es.caib.gestoli.logic.model.QualitatNoConformitat q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatNoConformitat noConformitatAmbId( java.lang.Long id ) ;

   /**
    * Cerca totes les noConformitats de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection noConformitatCercaTotsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Cerca totes les noConformitats d'un tipus de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection noConformitatCercaTotsPerTipus( java.lang.Long idEstabliment,java.lang.Long idTipus ) ;

   /**
    * Cerca totes les noConformitats d'un tipus de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection noConformitatCercaTotsPerControl( java.lang.Long idControl ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void noConformitatEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearNoConformitatAccio( es.caib.gestoli.logic.model.QualitatNoConformitatAccio q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatNoConformitatAccio noConformitatAccioAmbId( java.lang.Long id ) ;

   /**
    * Cerca totes les accions de la noConformitat <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection noConformitatAccioCercaTotsPerNoConformitat( java.lang.Long idNoConformitat ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long noConformitatAccioMaxCodiPerNoConformitat( java.lang.Long idNoConformitat ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void noConformitatAccioEsborrar( java.lang.Long id ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatDepartament departamentAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection departamentCercaTots(  ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatControl controlAmbId( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCC( es.caib.gestoli.logic.model.QualitatAPPCC q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCC aPPCCAmbId( java.lang.Long id ) ;

   /**
    * Cerca l'APPCC de l'establiment<!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCC aPPCCCercaPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCCProducte( es.caib.gestoli.logic.model.QualitatAPPCCProducte q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCProducte aPPCCProducteAmbId( java.lang.Long id ) ;

   /**
    * Cerca totes les accions de la noConformitat <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCProducteCercaTotsPerAPPCC( java.lang.Long idAPPCC ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aPPCCProducteEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCCEtapa( es.caib.gestoli.logic.model.QualitatAPPCCEtapa q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCEtapa aPPCCEtapaAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCEtapaCercaTotsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aPPCCEtapaEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCCEtapaPerill( es.caib.gestoli.logic.model.QualitatAPPCCEtapaPerill q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCEtapaPerill aPPCCEtapaPerillAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCEtapaPerillCercaTotsPerEtapa( java.lang.Long idEtapa ) ;

   /**
    * Cerca tots els perills de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCPerillCercaTotsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aPPCCEtapaPerillEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCCControl( es.caib.gestoli.logic.model.QualitatAPPCCControl q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCControl aPPCCControlAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCControlCercaTotsPerPerill( java.lang.Long idPerill ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCControlCercaPCCPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aPPCCControlEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCFitxaCControl( es.caib.gestoli.logic.model.QualitatAPPCCFitxaControl q ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCCFitxaControlHistoric( es.caib.gestoli.logic.model.QualitatAPPCCFitxaControlHistoric q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCFitxaControlHistoric aPPCCFitxaControlHistoricAmbId( java.lang.Long id ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCFitxaControl aPPCCFitxaControlAmbId( java.lang.Long id ) ;

   /**
    * Cerca la darrera fitxa de control del control<!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCFitxaControlHistoric aPPCCFitxaControlPerControl( java.lang.Long idControl ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCCPlaVerificacio( es.caib.gestoli.logic.model.QualitatAPPCCPlaVerificacio q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCPlaVerificacio aPPCCPlaVerificacioAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCPlaVerificacioCercaTotsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aPPCCPlaVerificacioEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAiguaSubministre( es.caib.gestoli.logic.model.QualitatAiguaSubministre q ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarAiguaSubministre( es.caib.gestoli.logic.model.QualitatAiguaSubministre q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaSubministre aiguaSubministreAmbId( java.lang.Long id ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaSubministre aiguaSubministreByEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAiguaPuntSortida( es.caib.gestoli.logic.model.QualitatAiguaPuntSortida q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaPuntSortida aiguaPuntSortidaAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aiguaPuntsSortidaPerEstabliment( java.lang.Long establimentId ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aiguaPuntSortidaEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAiguaControlAnalitic( es.caib.gestoli.logic.model.QualitatAiguaControlAnalitic q ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarAiguaControlAnalitic( es.caib.gestoli.logic.model.QualitatAiguaControlAnalitic q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaControlAnalitic aiguaControlAnaliticAmbId( java.lang.Long id ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaControlAnalitic aiguaControlAnaliticByEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAiguaControlOrganoleptic( es.caib.gestoli.logic.model.QualitatAiguaControlOrganoleptic q ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarAiguaControlOrganoleptic( es.caib.gestoli.logic.model.QualitatAiguaControlOrganoleptic q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaControlOrganoleptic aiguaControlOrganolepticAmbId( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAiguaControlAnaliticVerificacio( es.caib.gestoli.logic.model.QualitatAiguaControlAnaliticVerificacio q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaControlAnaliticVerificacio aiguaControlAnaliticVerificacioAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aiguaControlAnaliticVerificacioPerControl( java.lang.Long idControl ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aiguaControlAnaliticVerificacioEsborrar( java.lang.Long id ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAiguaControlOrganolepticVerificacio( es.caib.gestoli.logic.model.QualitatAiguaControlOrganolepticVerificacio q ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaControlOrganolepticVerificacio aiguaControlOrganolepticVerificacioAmbId( java.lang.Long id ) ;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aiguaControlOrganolepticVerificacioPerControl( java.lang.Long idControl ) ;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aiguaControlOrganolepticVerificacioEsborrar( java.lang.Long id ) ;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection netejaRealitzacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection netejaVerificacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection mantenimentRealitzacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection mantenimentVerificacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection controlPlaguesVerificacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection proveidorsVerificacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection controlAiguaVerificacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection APPCCControlCercaPendentsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection APPCCVerificacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Cerca totes les noConformitats no tancades de l'establiment <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection noConformitatsObertesPerEstabliment( java.lang.Long idEstabliment ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void setHibernateTemplate( org.springframework.orm.hibernate3.HibernateTemplate hibernateTemplate ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public org.springframework.orm.hibernate3.HibernateTemplate getHibernateTemplate(  ) ;

}
