/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Remote interface for OliQualitatEjb.
 */
public interface OliQualitatEjb
   extends javax.ejb.EJBObject
{
   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void ejbRemove(  )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void crearDescripcioInstalacio( es.caib.gestoli.logic.model.QualitatDescripcioInstalacio q )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarDescripcioInstalacio( es.caib.gestoli.logic.model.QualitatDescripcioInstalacio q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatDescripcioInstalacio descripcioInstalacioAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatDescripcioInstalacio descripcioInstalacioByEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long descripcioEquipCrear( es.caib.gestoli.logic.model.QualitatDescripcioEquip q )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarDescripcioEquip( es.caib.gestoli.logic.model.QualitatDescripcioEquip q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatDescripcioEquip getQualitatDescripcioEquipById( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection getQualitatDescripcioEquipsByEstabliment( java.lang.Long establimentId )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection vehiclesByEstabliment( java.lang.Long establimentId )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void qualitatDescripcioEquipEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearDescripcioPersonal( es.caib.gestoli.logic.model.QualitatDescripcioPersonal q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatDescripcioPersonal personalAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection personalCercaTotsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void personalEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Devuelve una lista de documentos
    * @return collection <!-- begin-xdoclet-definition -->
    */
   public java.util.List documentsByPersonal( java.lang.Long idPersonal )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarPuestoTreball( es.caib.gestoli.logic.model.QualitatPuestoTreball q )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPuestoTreball( es.caib.gestoli.logic.model.QualitatPuestoTreball q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPuestoTreball puestoAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tots els carrecs de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection puestoCercaTotsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot els carrecs de l'establiment per nivell Jerarquic<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection puestoCercaTotsPerNivell( java.lang.Long idEstabliment,java.lang.Integer nivell )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void puestoEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaFormacio( es.caib.gestoli.logic.model.QualitatPlaFormacio q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaFormacio formacioAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection formacioCercaTotsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void formacioEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearEvaluacio( es.caib.gestoli.logic.model.QualitatFormacioEvaluacio q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatFormacioEvaluacio evaluacioAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca totes les evaluacions de la formacio <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection evaluacioCercaTotsPerFormacio( java.lang.Long idFormacio )
      throws java.rmi.RemoteException;

   /**
    * Cerca totes les evaluacions del treballador <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection evaluacioCercaTotsPerTreballador( java.lang.Long idTreballador )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void evaluacioEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca totes les evaluacions del treballador <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long proveidorCrear( es.caib.gestoli.logic.model.QualitatProveidor q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatProveidor proveidorAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tots els proveidors de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection proveidorsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void proveidorEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca totes les evaluacions del treballador <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.GestorDocumentalInformacio informacioAmbId( java.lang.Integer id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public boolean usuariHaLeido( java.lang.Long idUsu,java.lang.Integer idInfo )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void usuariLeeInfo( java.lang.Long idUsu,es.caib.gestoli.logic.model.GestorDocumentalInformacio info )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.List documentsByInformacio( java.lang.Integer idInformacio )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.GestorDocumentalCategoriaInformacio categoriaInformacioAmbId( java.lang.Integer id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection categoriaInformacioFindAll(  )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection llistatInformacioFiltreIEstat( java.lang.Integer categoria,int estat )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection llistatInformacioIEstat( int estat )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection llistatInformacio(  )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public boolean existenInformacionesAsociadasCategoria( java.lang.Integer id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void categoriaInformacioEsborrar( java.lang.Integer id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Integer informacioCategoriaCrear( java.lang.String nom,java.lang.String desc )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void informacioCategoriaModificar( java.lang.Integer id,java.lang.String nom,java.lang.String desc )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public boolean existeOtraCategoriaConNombre( java.lang.String nom,java.lang.Integer id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void documentEsborrar( java.lang.Integer id )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.lang.Integer informacioCrear( es.caib.gestoli.logic.model.GestorDocumentalInformacio informacio )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public void informacioModificar( es.caib.gestoli.logic.model.GestorDocumentalInformacio informacio,java.lang.Boolean informar )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public void informacioEsborrar( es.caib.gestoli.logic.model.GestorDocumentalInformacio informacio )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public void documentCrear( es.caib.gestoli.logic.model.GestorDocumentalDocument document,es.caib.gestoli.logic.model.Arxiu arxiu )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public void documentModificar( es.caib.gestoli.logic.model.GestorDocumentalDocument document,es.caib.gestoli.logic.model.Arxiu arxiu )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.GestorDocumentalDocument documentAmbId( java.lang.Integer id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearSubministre( es.caib.gestoli.logic.model.QualitatSubministre q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatSubministre subministreAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tots els subministres d'un proveidor<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection subministrePerProveidor( java.lang.Long idProveidor )
      throws java.rmi.RemoteException;

   /**
    * Cerca tots els subministres d'un establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection subministresPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void subministreEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearProveidorRGSA( es.caib.gestoli.logic.model.QualitatProveidorRGSA q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatProveidorRGSA proveidorRGSAAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tots els proveidorRGSAs d'un proveidor<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection proveidorRGSAPerProveidor( java.lang.Long idProveidor )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void proveidorRGSAEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearProveidorAvaluacio( es.caib.gestoli.logic.model.QualitatProveidorAvaluacio q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatProveidorAvaluacio proveidorAvaluacioAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection avaluacionsPerProveidor( java.lang.Long idProveidor )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void proveidorAvaluacioEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca totes les evaluacions del treballador <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarPlaNeteja( es.caib.gestoli.logic.model.QualitatPlaNeteja q )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaManteniment( es.caib.gestoli.logic.model.QualitatPlaManteniment q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaManteniment mantenimentAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaNeteja( es.caib.gestoli.logic.model.QualitatPlaNeteja q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaNeteja plaNetejaAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection plansNetejaPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void plaNetejaEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaNetejaRealitzacio( es.caib.gestoli.logic.model.QualitatPlaNetejaRealitzacio q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaNetejaRealitzacio netejaRealitzacioAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection netejaRealitzacioPerPlaNeteja( java.lang.Long idManteniment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void netejaRealitzacioEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaNetejaVerificacio netejaVerificacioAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection netejaVerificacioPerPlaNeteja( java.lang.Long idNeteja )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void netejaVerificacioEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaNetejaVerificacio( es.caib.gestoli.logic.model.QualitatPlaNetejaVerificacio q )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection mantenimentCercaTotsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void mantenimentEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaMantenimentControl( es.caib.gestoli.logic.model.QualitatPlaMantenimentControl q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaMantenimentControl mantenimentControlAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection mantenimentControlCercaTotsPerManteniment( java.lang.Long idManteniment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void mantenimentControlEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearControlPlagues( es.caib.gestoli.logic.model.QualitatControlPlagues q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatControlPlagues controlPlaguesAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection controlPlaguesCercaTotsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void controlPlaguesEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearControlPlaguesVerificacio( es.caib.gestoli.logic.model.QualitatControlPlaguesVerificacio q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatControlPlaguesVerificacio controlPlaguesVerificacioAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection controlPlaguesVerificacioCercaTotsPerPlaga( java.lang.Long idPlaga )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void controlPlaguesVerificacioEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearPlaControlTransport( es.caib.gestoli.logic.model.QualitatPlaControlTransport q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatPlaControlTransport plaControlTransportAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection plansControlTransportPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void plaControlTransportEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearNoConformitat( es.caib.gestoli.logic.model.QualitatNoConformitat q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatNoConformitat noConformitatAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca totes les noConformitats de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection noConformitatCercaTotsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Cerca totes les noConformitats d'un tipus de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection noConformitatCercaTotsPerTipus( java.lang.Long idEstabliment,java.lang.Long idTipus )
      throws java.rmi.RemoteException;

   /**
    * Cerca totes les noConformitats d'un tipus de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection noConformitatCercaTotsPerControl( java.lang.Long idControl )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void noConformitatEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearNoConformitatAccio( es.caib.gestoli.logic.model.QualitatNoConformitatAccio q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatNoConformitatAccio noConformitatAccioAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca totes les accions de la noConformitat <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection noConformitatAccioCercaTotsPerNoConformitat( java.lang.Long idNoConformitat )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long noConformitatAccioMaxCodiPerNoConformitat( java.lang.Long idNoConformitat )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void noConformitatAccioEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatDepartament departamentAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection departamentCercaTots(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatControl controlAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCC( es.caib.gestoli.logic.model.QualitatAPPCC q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCC aPPCCAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca l'APPCC de l'establiment<!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCC aPPCCCercaPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCCProducte( es.caib.gestoli.logic.model.QualitatAPPCCProducte q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCProducte aPPCCProducteAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca totes les accions de la noConformitat <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCProducteCercaTotsPerAPPCC( java.lang.Long idAPPCC )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aPPCCProducteEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCCEtapa( es.caib.gestoli.logic.model.QualitatAPPCCEtapa q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCEtapa aPPCCEtapaAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCEtapaCercaTotsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aPPCCEtapaEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCCEtapaPerill( es.caib.gestoli.logic.model.QualitatAPPCCEtapaPerill q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCEtapaPerill aPPCCEtapaPerillAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCEtapaPerillCercaTotsPerEtapa( java.lang.Long idEtapa )
      throws java.rmi.RemoteException;

   /**
    * Cerca tots els perills de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCPerillCercaTotsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aPPCCEtapaPerillEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCCControl( es.caib.gestoli.logic.model.QualitatAPPCCControl q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCControl aPPCCControlAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCControlCercaTotsPerPerill( java.lang.Long idPerill )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCControlCercaPCCPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aPPCCControlEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCFitxaCControl( es.caib.gestoli.logic.model.QualitatAPPCCFitxaControl q )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCCFitxaControlHistoric( es.caib.gestoli.logic.model.QualitatAPPCCFitxaControlHistoric q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCFitxaControlHistoric aPPCCFitxaControlHistoricAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCFitxaControl aPPCCFitxaControlAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca la darrera fitxa de control del control<!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCFitxaControlHistoric aPPCCFitxaControlPerControl( java.lang.Long idControl )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAPPCCPlaVerificacio( es.caib.gestoli.logic.model.QualitatAPPCCPlaVerificacio q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAPPCCPlaVerificacio aPPCCPlaVerificacioAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aPPCCPlaVerificacioCercaTotsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aPPCCPlaVerificacioEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAiguaSubministre( es.caib.gestoli.logic.model.QualitatAiguaSubministre q )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarAiguaSubministre( es.caib.gestoli.logic.model.QualitatAiguaSubministre q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaSubministre aiguaSubministreAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaSubministre aiguaSubministreByEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAiguaPuntSortida( es.caib.gestoli.logic.model.QualitatAiguaPuntSortida q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaPuntSortida aiguaPuntSortidaAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aiguaPuntsSortidaPerEstabliment( java.lang.Long establimentId )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aiguaPuntSortidaEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAiguaControlAnalitic( es.caib.gestoli.logic.model.QualitatAiguaControlAnalitic q )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarAiguaControlAnalitic( es.caib.gestoli.logic.model.QualitatAiguaControlAnalitic q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaControlAnalitic aiguaControlAnaliticAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaControlAnalitic aiguaControlAnaliticByEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAiguaControlOrganoleptic( es.caib.gestoli.logic.model.QualitatAiguaControlOrganoleptic q )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long actualitzarAiguaControlOrganoleptic( es.caib.gestoli.logic.model.QualitatAiguaControlOrganoleptic q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaControlOrganoleptic aiguaControlOrganolepticAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAiguaControlAnaliticVerificacio( es.caib.gestoli.logic.model.QualitatAiguaControlAnaliticVerificacio q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaControlAnaliticVerificacio aiguaControlAnaliticVerificacioAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aiguaControlAnaliticVerificacioPerControl( java.lang.Long idControl )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aiguaControlAnaliticVerificacioEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public java.lang.Long crearAiguaControlOrganolepticVerificacio( es.caib.gestoli.logic.model.QualitatAiguaControlOrganolepticVerificacio q )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.QualitatAiguaControlOrganolepticVerificacio aiguaControlOrganolepticVerificacioAmbId( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca tot el personal de l'establiment<!-- begin-xdoclet-definition -->
    */
   public java.util.Collection aiguaControlOrganolepticVerificacioPerControl( java.lang.Long idControl )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public void aiguaControlOrganolepticVerificacioEsborrar( java.lang.Long id )
      throws java.rmi.RemoteException;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection netejaRealitzacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection netejaVerificacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection mantenimentRealitzacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection mantenimentVerificacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection controlPlaguesVerificacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection proveidorsVerificacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection controlAiguaVerificacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection APPCCControlCercaPendentsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Cerca les tasques pendents dels plans de NetejaRealitzacio associats a un establiment. <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection APPCCVerificacioCercaPendentsPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Cerca totes les noConformitats no tancades de l'establiment <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection noConformitatsObertesPerEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void setHibernateTemplate( org.springframework.orm.hibernate3.HibernateTemplate hibernateTemplate )
      throws java.rmi.RemoteException;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public org.springframework.orm.hibernate3.HibernateTemplate getHibernateTemplate(  )
      throws java.rmi.RemoteException;

}
