/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Local home interface for OliQualitatEjb.
 */
public interface OliQualitatEjbLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliQualitatEjbLocal";
   public static final String JNDI_NAME="OliQualitatEjbLocal";

   public es.caib.gestoli.logic.interfaces.OliQualitatEjbLocal create()
      throws javax.ejb.CreateException;

}
