/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Remote interface for OliSistraEjb.
 */
public interface OliSistraEjb
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    */
   public void ejbRemove(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.Establiment establimentAmbCifNifResponsable( java.lang.String cif )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection findEntradesOlivaEntreDates( java.util.Date dataInici,java.util.Date dataFi,java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection findElaboracionsEntreDates( java.util.Date dataInici,java.util.Date dataFi,java.lang.Long idEstabliment,boolean asc,java.lang.Boolean valid )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection findSortidesLotEntreDates( java.util.Date dataInici,java.util.Date dataFi,java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection findSortidesDipositEntreDates( java.util.Date dataInici,java.util.Date dataFi,java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * Busca las salidas de depositos entre 2 fechas para un establecimiento <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection getSortidesDipositEntreFechasAndEstablecimiento( java.util.Date finicio,java.util.Date ffin,java.lang.Long idEst,java.lang.Boolean valid )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection findExistenciesDipositsByEstablimentCategoriasAndData( java.lang.Long establimentId,java.lang.Object[] categorias,java.util.Date data )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection findExistenciesLotsByEstablimentCategoriasAndData( java.lang.Long establimentId,java.lang.Object[] categorias,java.util.Date data )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection findAllCampanyes(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.Date findDataFiCampanya( java.lang.Long idCampanya )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection findLotsByEstablimentEntreDates( java.lang.Long idEstabliment,java.util.Date dataInici,java.util.Date dataFi,java.lang.Boolean valid )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection findExistenciesLotsByEstabliment( java.lang.Long establimentId )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection findDipositsActiusByEstabliment( java.lang.Long establimentId )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.List findEtiquetatgesByEstabliment( java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.util.Collection movimentsEntreEstablimentsEntradaConsulta( java.util.Date dataInici,java.util.Date dataFi,java.lang.Long idEstabliment )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.EntradaDiposit findEntradaDipositByTraza( java.lang.Long idTraza )
      throws java.rmi.RemoteException;

   /**
    * set the hibernate template.
    * @param hibernateTemplate the hibernate spring template. <!-- begin-xdoclet-definition -->
    */
   public void setHibernateTemplate( org.springframework.orm.hibernate3.HibernateTemplate hibernateTemplate )
      throws java.rmi.RemoteException;

   /**
    * get the hibernate template.
    * @return the hibernate spring template. <!-- begin-xdoclet-definition -->
    */
   public org.springframework.orm.hibernate3.HibernateTemplate getHibernateTemplate(  )
      throws java.rmi.RemoteException;

}
