/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Home interface for OliSistraEjb.
 */
public interface OliSistraEjbHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliSistraEjb";
   public static final String JNDI_NAME="OliSistraEjb";

   public es.caib.gestoli.logic.interfaces.OliSistraEjb create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
