/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Home interface for OliUsuariEjb.
 */
public interface OliUsuariEjbHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliUsuariEjb";
   public static final String JNDI_NAME="OliUsuariEjb";

   public es.caib.gestoli.logic.interfaces.OliUsuariEjb create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
