/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Local interface for OliUsuariEjb.
 */
public interface OliUsuariEjbLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Emmagatzema el SessionContext per poder-lo emprar als mètodes de negoci de l'EJB. <!-- begin-xdoclet-definition -->
    */
   public void setSessionContext( javax.ejb.SessionContext context ) ;

   /**
    * Només serveix per poder especificar els permisos amb xdoclet. <!-- begin-xdoclet-definition -->
    */
   public void ejbRemove(  ) ;

   /**
    * Retorna el registre de tipus usuari que té el login especificat.
    * @return el registre de tipus usuari <!-- begin-xdoclet-definition -->
    */
   public es.caib.gestoli.logic.model.Usuari verificaLogin(  ) ;

   /**
    * Comprova si l'establiment és correcte per un determinat usuari
    * @param idEstabliment
    * @param usuari
    * @return <!-- begin-xdoclet-definition -->
    */
   public boolean verificaEstabliment( java.lang.Long idEstabliment,java.lang.Long idUsuari ) ;

   /**
    * Comprova si l'olivicultor és correcte per un determinat usuari
    * @param idOlivicultor
    * @param usuari
    * @return <!-- begin-xdoclet-definition -->
    */
   public boolean verificaOlivicultor( java.lang.Long idOlivicultor,java.lang.Long idUsuari ) ;

   /**
    * Comprova si un grup és correcte per un determinat usuari.
    * @param idGrup
    * @param usuari
    * @return <!-- begin-xdoclet-definition -->
    */
   public boolean verificaGrup( java.lang.Long idGrup,java.lang.Long idUsuari ) ;

   /**
    * Comprueba si existen olivicultores altaDO en la BBDD <!-- begin-xdoclet-definition -->
    */
   public boolean existenOlivicultoresAltaDOConFincas(  ) ;

   /**
    * set the hibernate template.
    * @param hibernateTemplate the hibernate spring template. <!-- begin-xdoclet-definition -->
    */
   public void setHibernateTemplate( org.springframework.orm.hibernate3.HibernateTemplate hibernateTemplate ) ;

   /**
    * get the hibernate template.
    * @return the hibernate spring template. <!-- begin-xdoclet-definition -->
    */
   public org.springframework.orm.hibernate3.HibernateTemplate getHibernateTemplate(  ) ;

}
