/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.interfaces;

/**
 * Local home interface for OliUsuariEjb.
 */
public interface OliUsuariEjbLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OliUsuariEjbLocal";
   public static final String JNDI_NAME="OliUsuariEjbLocal";

   public es.caib.gestoli.logic.interfaces.OliUsuariEjbLocal create()
      throws javax.ejb.CreateException;

}
