/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.ejb;

/**
 * Session layer for OliConsultaEjb.
 */
public class OliConsultaEjbSession
   extends es.caib.gestoli.logic.ejb.OliConsultaEjbBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
      super.ejbRemove();
   }

}
