/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.ejb;

/**
 * Session layer for OliProcessosEjb.
 * @generated 
 */
public class OliProcessosEjbSession
   extends es.caib.gestoli.logic.ejb.OliProcessosEjbBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
      super.ejbRemove();
   }

}
