/*
 * Generated by XDoclet - Do not edit!
 */
package es.caib.gestoli.logic.ejb;

/**
 * Session layer for OliQualitatEjb.
 */
public class OliQualitatEjbSession
   extends es.caib.gestoli.logic.ejb.OliQualitatEjbBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
      super.ejbRemove();
   }

}
